os: linux
dist: xenial
language: generic
git:
  depth: 1

branches:
  only:
  - dev
  - master

jobs:
  include:
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Release
      - MARIAFIX=true
      - TGS4_TEST_DATABASE_TYPE=MySql
      - TGS4_TEST_CONNECTION_STRING="server=127.0.0.1;uid=testuser;pwd=password;database=tgs_test"
      name: "MariaDB Integration Test"
      language: csharp
      mono: none
      dotnet: 3.1
      cache:
        directories:
          - $HOME/.nuget/packages:
      addons:
        mariadb: '10.5'
        apt:
          packages:
            - libc6-i386
            - libstdc++6:i386
            - gdb
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Release
      - TGS4_TEST_DATABASE_TYPE=Sqlite
      - TGS4_TEST_CONNECTION_STRING="Data Source=TravisTestDB.sqlite3;Mode=ReadWriteCreate"
      name: "Sqlite Integration Test"
      language: csharp
      mono: none
      dotnet: 3.1
      cache:
        directories:
          - $HOME/.nuget/packages:
      addons:
        apt:
          packages:
            - libc6-i386
            - libstdc++6:i386
            - gdb
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=false
      - POSTGRESFIX=true
      - CONFIG=Release
      - TGS4_TEST_DATABASE_TYPE=PostgresSql
      - TGS4_TEST_CONNECTION_STRING="Application Name=tgstation-server;Port=5433;Host=127.0.0.1;Username=testuser;Password=password;Database=TGS_Test"
      - PGPORT=5433
      name: "PostgresSql Integration Test"
      language: csharp
      mono: none
      dotnet: 3.1
      cache:
        directories:
          - $HOME/.nuget/packages:
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - libc6-i386
            - libstdc++6:i386
            - gdb
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Debug
      name: "Debug Unit Tests"
      language: csharp
      mono: none
      dotnet: 3.1
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Release
      name: "Release Unit Tests"
      language: csharp
      mono: none
      dotnet: 3.1
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DoxGeneration=false
      - DockerBuild=true
      name: "Docker Build"
      services:
        - docker
    - env:
      - DoxGeneration=true
      name: "Dox Generation"
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
    - env:
      - DoxGeneration=false
      - DockerBuild=false
      - DMAPI=true
      - BYOND_MAJOR="513"
      - BYOND_MINOR="1517"
      - DMEName="tests/DMAPI/travistester.dme"
      name: "DMAPI Unit Tests"
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      addons:
        apt:
          packages:
            - libc6-i386
            - libstdc++6:i386

before_install:
  - if [ $POSTGRESFIX = true ]; then sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"; fi
  - if [ $POSTGRESFIX = true ]; then sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"; fi
  - if [ $MARIAFIX = true ]; then sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'localhost' IDENTIFIED BY 'password';"; fi

install:
  - if [ $DoxGeneration = false ] && [ $DockerBuild = false ] && [ $DMAPI = true ]; then build/install_byond.sh; fi
  - if [ $DoxGeneration = false ] && [ $DockerBuild = false ] && [ $DMAPI = false ]; then dotnet restore tgstation-server.sln; fi

script:
  - if [ $DoxGeneration = false ] && [ $DockerBuild = false ] && [ $DMAPI = true ]; then tests/DMAPI/BasicOperation/build_byond.sh || travis_terminate 1; fi
  - if [ $DoxGeneration = false ] && [ $DockerBuild = false ] && [ $DMAPI = false ]; then build/test_core.sh; fi
  - if [ $DoxGeneration = false ] && [ $DockerBuild = true ]; then docker build . -f build/Dockerfile; fi
  - if [ $DoxGeneration = true ]; then build/build_dox.sh; fi
