os: linux
dist: xenial
language: generic
git:
  depth: 1

branches:
  only:
  - dev
  - master

env:
  - TGS4_TEST_TEMP_DIRECTORY=/tgs4_test

jobs:
  include:
    - env:
      - DockerBuild=false
      - DMAPI=true
      - BYOND_MAJOR="513"
      - BYOND_MINOR="1517"
      - DMEName="tests/DMAPI/travistester.dme"
      name: "DMAPI Unit Tests"
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

      addons:
        apt:
          packages:
            - libc6-i386
            - libstdc++6:i386
    - env:
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Debug
      name: "Test Server Debug"
      language: csharp
      mono: none
      dotnet: 3.1
      services:
        - mysql
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DockerBuild=false
      - DMAPI=false
      - CONFIG=Release
      name: "Test Server Release"
      language: csharp
      mono: none
      dotnet: 3.1
      services:
        - mysql
      cache:
        directories:
          - $HOME/.nuget/packages:
    - env:
      - DockerBuild=true
      name: "Docker Build"
      services:
        - docker

install:
  - if [ $DockerBuild = false ] && [ $DMAPI = true ]; then build/install_byond.sh; fi
  - if [ $DockerBuild = false ] && [ $DMAPI = false ]; then dotnet restore tgstation-server.sln; fi

script:
  - if [ $DockerBuild = false ] && [ $DMAPI = true ]; then tests/DMAPI/BasicOperation/build_byond.sh || travis_terminate 1; fi
  - if [ $DockerBuild = false ] && [ $DMAPI = false ]; then build/test_core.sh; fi
  - if [ $DockerBuild = true ]; then docker build . -f build/Dockerfile; fi
