name: 'CI'

on:
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev
    - master

env:
  TGS4_TEST_DISCORD_CHANNEL: ${{ secrets.DISCORD_CHANNEL_ID }}
  TGS4_TEST_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  TGS4_TEST_IRC_CHANNEL: ${{ secrets.IRC_CHANNEL }}
  TGS4_TEST_IRC_CONNECTION_STRING: ${{ secrets.IRC_CONNECTION_STRING }}
  TGS4_TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  debug-echo:
    name: Echo Context Stuff
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.ref }}
        echo ${{ github.event.ref }}
        echo ${{ github.event.commit.message }}
        echo ${{ github.event.head_commit.message }}
        echo ${{ github.event.after.message }}
